server:
    port: 8080

spring:
    datasource:
        username: root
        password: Vitalex88
        url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
jpa:
    properties:
        hibernate: